genome:
  ensembl: mm39
  release: 115

trim_galore:
  extra: "-q 20 --nextera"

bwa_mem2:
  extra: "-M"

macs2:
  extra: "-f BAMPE --nomodel --shift -37 --extsize 73 --keep-dup all -q 0.05 -g mm"

ataqv:
  extra: ""
